---
title: "cellchat"
output: html_document
date: "2023-03-29"
---

```{r}
#############################
#Cellchat ###################
#############################
library(Seurat)
library(dplyr)
library(SeuratData)
library(patchwork) #最强大的拼图包
library(ggplot2)
library(CellChat)
library(ggalluvial)
library(svglite)
#CellChat需要两个输入:

#一个是细胞的基因表达数据，
#另一个是细胞标签(即细胞标签)。
#对于基因表达数据矩阵，基因应该在带有行名的行中，cell应该在带有名称的列中。CellChat分析的输入是均#一化的数据(Seurat@assay$RNA@data)。如果用户提供counts数据，可以用normalizeData函数来均一化。对于#细胞的信息，需要一个带有rownames的数据格式作为CellChat的输入。
cellchat <- createCellChat(object=compare,group.by = "celltype")
cellchat
summary(cellchat)
str(cellchat)
levels(cellchat@idents)
groupSize <- as.numeric(table(cellchat@idents)) 
groupSize
```

```{r}
CellChatDB <- CellChatDB.human
#导入小鼠是CellChatDB <-CellChatDB.mouse
str(CellChatDB)#查看数据库信息
#包含interaction、complex、cofactor和geneInfo这4个dataframe
colnames(CellChatDB$interaction) 
CellChatDB$interaction[1:4,1:4]
head(CellChatDB$cofactor)
head(CellChatDB$complex)
head(CellChatDB$geneInfo)
#dev.new() #下一步不出图的时候运行
showDatabaseCategory(CellChatDB)
```

```{r}
unique(CellChatDB$interaction$annotation)#查看可以选择的侧面，也就是上图左中的三种
#选择"Secreted Signaling"进行后续细胞互作分析
CellChatDB.use <-subsetDB(CellChatDB, search = "Secreted Signaling")
# use all CellChatDB for cell-cell communication analysis
# CellChatDB.use <- CellChatDB # simply use the default CellChatDB
# set the used database in the object
cellchat@DB <- CellChatDB.use
 # set the used database in the object
```

```{r}
## 在矩阵的所有的基因中提取signaling gene，结果保存在data.signaling(13714个基因，过滤完只有270个）
cellchat <- subsetData(cellchat)
#相当于Seurat的FindMarkers，找每个细胞群中高表达的配体受体
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat) #Identify over-expressed ligand-receptor interactions  (pairs) within the used CellChatDB
#上一步运行的结果储存在cellchat@LR$LRsig
cellchat <- projectData(cellchat, PPI.human)
#找到配体受体关系后，projectData将配体受体对的表达值投射到PPI上，来对@data.signaling中的表达值进行校正。结果保存在@data.project
```




```{r}
######################################
#Part Ⅱ：推断配体-受体细胞通讯网络
######################################
#1. 计算通信概率，并推断信号网络
#根据表达值推测细胞互作的概率（cellphonedb是用平均表达值代表互作强度）。
cellchat <- computeCommunProb(cellchat, raw.use = FALSE,population.size = TRUE)#如果不想用上一步PPI矫正的结果，raw.use = TRUE即可。
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat <- filterCommunication(cellchat, min.cells = 10)
df.net <- subsetCommunication(cellchat)
write.csv(df.net, "net_lr.csv")
```
```{r}
#2. 计算信号通路水平上的细胞间通讯
cellchat <- computeCommunProbPathway(cellchat)
df.netp <- subsetCommunication(cellchat, slot.name = "netP")
write.csv(df.netp, "net_pathway.csv")
```

```{r}
#3.计算聚合的细胞间通讯网络
#统计细胞和细胞之间通信的数量（有多少个配体-受体对）和强度（概率）
cellchat <- aggregateNet(cellchat)
#计算每种细胞各有多少个
groupSize <- as.numeric(table(cellchat@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat@net$count,vertex.weight = groupSize, weight.scale = T,label.edge= F, title.name = "Number of interactions")
#ggsave("netVisual_circle.png",netVisual_circle)
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T,label.edge= F,title.name = "Interaction weights/strength")
#save as TIL/net_number_strength.pdf
```

```{r}
## 检查每种细胞发出的信号 （每种细胞和其他细胞的互作情况）
mat <- cellchat@net$count
par(mfrow = c(3,3), xpd=TRUE)
for (i in 1:nrow(mat)) {
  # i = 1
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <-  mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, arrow.width = 0.2,arrow.size = 0.1,edge.weight.max = max(mat),title.name = rownames(mat)[i])}

```
```{r}
#如果只想关注某一类细胞群相关的通讯情况
mat <- cellchat@net$weight
mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
mat2["Mesenchymal cells", ] <- mat["Mesenchymal cells", ]
netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, 
                 edge.weight.max = max(mat), title.name = "Mesenchymal cells")
```









```{r}
####################################
#Part Ⅲ：细胞间通讯网络的可视化
####################################
#在推断出细胞间通信网络后，CellChat 为进一步的数据探索、分析和可视化提供了各种功能。
#CellChat 提供了几种可视化细胞间通信网络的方法，包括层次图、圆图、弦图和气泡图。
#CellChat 提供了一个易于使用的工具，用于提取和可视化推断网络的高阶信息。例如，它可以方便地预测细
#胞群的主要信号输入和输出，以及这些群和信号如何协调在一起以实现功能。
#CellChat 可以通过结合社交网络分析、模式识别和流形学习方法，使用集成方法对推断的细胞-细胞通信网络#进行定量表征和比较。
```

```{r}
#使用层次图、圈图或弦图可视化每个信号通路
## 选择其中一个信号，比如说TGFb
pathways.show <- c("TGFb")
```

```{r}
# Hierarchy plot
# Here we define `vertex.receive` so that the left portion of the hierarchy plot shows signaling to fibroblast and the right portion shows signaling to immune cells 
vertex.receiver = seq(1,2) # a numeric vector. 
#svglite(file ="a.pdf")
pdf("network.pdf", width=7, height=7)
netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver,layout = "hierarchy")
dev.off()
```

```{r}
# Circle plot
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```
```{r}
# Chord diagram
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
```

```{r}
# Heatmap
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
#> Do heatmap based on a single object
```

```{r}
#计算受配体对整个信号通路的贡献，并可视化单个配体-受体对介导的细胞-细胞通讯
netAnalysis_contribution(cellchat, signaling = pathways.show)
```

```{r}
pairLR.TGFb <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.TGFb[1,] # show one ligand-receptor pair
# Hierarchy plot
vertex.receiver = seq(1,2) # a numeric vector
netVisual_individual(cellchat, signaling = pathways.show,  pairLR.use = LR.show, vertex.receiver = vertex.receiver)
#> [[1]]
# Circle plot
netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "circle")
```

```{r}
# Chord diagram
netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "chord")
```
```{r}
#自动保存所有推断网络图以便快速探索
# Access all the signaling pathways showing significant communications
pathways.show.all <- cellchat@netP$pathways
# check the order of cell identity to set suitable vertex.receiver
levels(cellchat@idents)
vertex.receiver = seq(1,2)
for (i in 1:length(pathways.show.all)) {
  # Visualize communication network associated with both signaling pathway and individual L-R pairs
  netVisual(cellchat, signaling = pathways.show.all[i], vertex.receiver = vertex.receiver, layout = "hierarchy")
  # Compute and visualize the contribution of each ligand-receptor pair to the overall signaling pathway
  gg <- netAnalysis_contribution(cellchat, signaling = pathways.show.all[i])
  ggsave(filename=paste0(pathways.show.all[i], "_L-R_contribution.pdf"), plot=gg, width = 3, height = 2, units = 'in', dpi = 300)
}
```

```{r}
#可视化由多个受配体或信号通路介导的细胞间通讯
# 气泡图（全部配体-受体）

levels(cellchat@idents)
# show all the significant interactions (L-R pairs)

# 需要制定受体细胞核配体细胞
p=netVisual_bubble(cellchat, sources.use = c(3,5,7,8,9),
                   targets.use = c(1,2,4,6),remove.isolate = FALSE)
p
ggsave("p.png",p,width = 10, height = 20, dpi = 250)
```
```{r}
#比如指定CCL和CXCL这两个信号通路
netVisual_bubble(cellchat,sources.use = c(3,5,7,8,9),targets.use = c(1,2,4,6),
                 signaling = c("CCL","CXCL"),remove.isolate = F)
```

